/* Generated By:JJTree&JavaCC: Do not edit this line. CCJSqlParserConstants.java */
/*
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2014 JSQLParser
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */

package net.sf.jsqlparser.parser;

public interface CCJSqlParserConstants {

  int EOF = 0;
  int K_AS = 5;
  int K_BY = 6;
  int K_DO = 7;
  int K_IS = 8;
  int K_IN = 9;
  int K_OR = 10;
  int K_ON = 11;
  int K_ALL = 12;
  int K_AND = 13;
  int K_ANY = 14;
  int K_KEY = 15;
  int K_NOT = 16;
  int K_SET = 17;
  int K_ASC = 18;
  int K_TOP = 19;
  int K_PERCENT = 20;
  int K_END = 21;
  int K_DESC = 22;
  int K_INTO = 23;
  int K_NULL = 24;
  int K_LIKE = 25;
  int K_ILIKE = 26;
  int K_DROP = 27;
  int K_JOIN = 28;
  int K_LEFT = 29;
  int K_CROSS = 30;
  int K_FROM = 31;
  int K_OPEN = 32;
  int K_CASE = 33;
  int K_WHEN = 34;
  int K_THEN = 35;
  int K_ELSE = 36;
  int K_SOME = 37;
  int K_FULL = 38;
  int K_WITH = 39;
  int K_TABLE = 40;
  int K_VIEW = 41;
  int K_WHERE = 42;
  int K_FOR = 43;
  int K_PIVOT = 44;
  int K_XML = 45;
  int K_USING = 46;
  int K_UNION = 47;
  int K_GROUP = 48;
  int K_BEGIN = 49;
  int K_INDEX = 50;
  int K_INNER = 51;
  int K_LIMIT = 52;
  int K_OUTER = 53;
  int K_ORDER = 54;
  int K_RIGHT = 55;
  int K_VALUE = 56;
  int K_DELETE = 57;
  int K_CREATE = 58;
  int K_SELECT = 59;
  int K_OFFSET = 60;
  int K_EXISTS = 61;
  int K_HAVING = 62;
  int K_INSERT = 63;
  int K_UPDATE = 64;
  int K_VALUES = 65;
  int K_ESCAPE = 66;
  int K_PRIMARY = 67;
  int K_NATURAL = 68;
  int K_REPLACE = 69;
  int K_BETWEEN = 70;
  int K_TRUNCATE = 71;
  int K_DISTINCT = 72;
  int K_INTERSECT = 73;
  int K_CAST = 74;
  int K_EXCEPT = 75;
  int K_MINUS = 76;
  int K_OVER = 77;
  int K_PARTITION = 78;
  int K_EXTRACT = 79;
  int K_LATERAL = 80;
  int K_MATERIALIZED = 81;
  int K_INTERVAL = 82;
  int K_FOREIGN = 83;
  int K_CONSTRAINT = 84;
  int K_REFERENCES = 85;
  int K_CHARACTER = 86;
  int K_VARYING = 87;
  int K_START = 88;
  int K_CONNECT = 89;
  int K_PRIOR = 90;
  int K_NOCYCLE = 91;
  int K_SIBLINGS = 92;
  int K_ALTER = 93;
  int K_ADD = 94;
  int K_COLUMN = 95;
  int K_NULLS = 96;
  int K_FIRST = 97;
  int K_LAST = 98;
  int K_ROWS = 99;
  int K_RANGE = 100;
  int K_UNBOUNDED = 101;
  int K_PRECEDING = 102;
  int K_FOLLOWING = 103;
  int K_CURRENT = 104;
  int K_ROW = 105;
  int K_RETURNING = 106;
  int K_BINARY = 107;
  int K_REGEXP = 108;
  int K_UNLOGGED = 109;
  int K_EXEC = 110;
  int K_EXECUTE = 111;
  int K_FETCH = 112;
  int K_NEXT = 113;
  int K_ONLY = 114;
  int K_COMMIT = 115;
  int K_UNIQUE = 116;
  int K_WITHIN = 117;
  int K_IF = 118;
  int K_RECURSIVE = 119;
  int K_OF = 120;
  int K_KEEP = 121;
  int K_GROUP_CONCAT = 122;
  int K_SEPARATOR = 123;
  int K_SKIP = 124;
  int K_MERGE = 125;
  int K_MATCHED = 126;
  int K_CASCADE = 127;
  int K_RESTRICT = 128;
  int S_DOUBLE = 129;
  int S_LONG = 130;
  int DIGIT = 131;
  int S_HEX = 132;
  int HEX_VALUE = 133;
  int LINE_COMMENT = 134;
  int MULTI_LINE_COMMENT = 135;
  int S_IDENTIFIER = 136;
  int LETTER = 137;
  int PART_LETTER = 138;
  int S_CHAR_LITERAL = 139;
  int S_QUOTED_IDENTIFIER = 140;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"AS\"",
    "\"BY\"",
    "\"DO\"",
    "\"IS\"",
    "\"IN\"",
    "\"OR\"",
    "\"ON\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"KEY\"",
    "\"NOT\"",
    "\"SET\"",
    "\"ASC\"",
    "\"TOP\"",
    "\"PERCENT\"",
    "\"END\"",
    "\"DESC\"",
    "\"INTO\"",
    "\"NULL\"",
    "\"LIKE\"",
    "\"ILIKE\"",
    "\"DROP\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"CROSS\"",
    "\"FROM\"",
    "\"OPEN\"",
    "\"CASE\"",
    "\"WHEN\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"SOME\"",
    "\"FULL\"",
    "\"WITH\"",
    "\"TABLE\"",
    "\"VIEW\"",
    "\"WHERE\"",
    "\"FOR\"",
    "\"PIVOT\"",
    "\"XML\"",
    "\"USING\"",
    "\"UNION\"",
    "\"GROUP\"",
    "\"BEGIN\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"LIMIT\"",
    "\"OUTER\"",
    "\"ORDER\"",
    "\"RIGHT\"",
    "\"VALUE\"",
    "\"DELETE\"",
    "\"CREATE\"",
    "\"SELECT\"",
    "\"OFFSET\"",
    "\"EXISTS\"",
    "\"HAVING\"",
    "\"INSERT\"",
    "\"UPDATE\"",
    "\"VALUES\"",
    "\"ESCAPE\"",
    "\"PRIMARY\"",
    "\"NATURAL\"",
    "\"REPLACE\"",
    "\"BETWEEN\"",
    "\"TRUNCATE\"",
    "\"DISTINCT\"",
    "\"INTERSECT\"",
    "\"CAST\"",
    "\"EXCEPT\"",
    "\"MINUS\"",
    "\"OVER\"",
    "\"PARTITION\"",
    "\"EXTRACT\"",
    "\"LATERAL\"",
    "\"MATERIALIZED\"",
    "\"INTERVAL\"",
    "\"FOREIGN\"",
    "\"CONSTRAINT\"",
    "\"REFERENCES\"",
    "\"CHARACTER\"",
    "\"VARYING\"",
    "\"START\"",
    "\"CONNECT\"",
    "\"PRIOR\"",
    "\"NOCYCLE\"",
    "\"SIBLINGS\"",
    "\"ALTER\"",
    "\"ADD\"",
    "\"COLUMN\"",
    "\"NULLS\"",
    "\"FIRST\"",
    "\"LAST\"",
    "\"ROWS\"",
    "\"RANGE\"",
    "\"UNBOUNDED\"",
    "\"PRECEDING\"",
    "\"FOLLOWING\"",
    "\"CURRENT\"",
    "\"ROW\"",
    "\"RETURNING\"",
    "\"BINARY\"",
    "\"REGEXP\"",
    "\"UNLOGGED\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"FETCH\"",
    "\"NEXT\"",
    "\"ONLY\"",
    "\"COMMIT\"",
    "\"UNIQUE\"",
    "\"WITHIN\"",
    "\"IF\"",
    "\"RECURSIVE\"",
    "\"OF\"",
    "\"KEEP\"",
    "\"GROUP_CONCAT\"",
    "\"SEPARATOR\"",
    "\"SKIP\"",
    "\"MERGE\"",
    "\"MATCHED\"",
    "\"CASCADE\"",
    "\"RESTRICT\"",
    "<S_DOUBLE>",
    "<S_LONG>",
    "<DIGIT>",
    "<S_HEX>",
    "<HEX_VALUE>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\".\"",
    "\"?\"",
    "\"+\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"!=\"",
    "\"@@\"",
    "\"~\"",
    "\"~*\"",
    "\"!~\"",
    "\"!~*\"",
    "\"||\"",
    "\"|\"",
    "\"&\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"{d\"",
    "\"}\"",
    "\"{t\"",
    "\"{ts\"",
    "\"::\"",
    "\":\"",
    "\"@\"",
    "\"->\"",
    "\"{fn\"",
    "\"[\"",
    "\"]\"",
  };

}
