/* Generated By:JJTree: Do not edit this line. .\CCJSqlParserTreeConstants.java */

package net.sf.jsqlparser.parser;

public interface CCJSqlParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTSINGLESTATEMENT = 1;
  public int JJTSTATEMENTS = 2;
  public int JJTSET = 3;
  public int JJTUPDATE = 4;
  public int JJTREPLACE = 5;
  public int JJTLISTEXPRESSIONITEM = 6;
  public int JJTINSERT = 7;
  public int JJTDELETE = 8;
  public int JJTMERGE = 9;
  public int JJTMERGEUPDATECLAUSE = 10;
  public int JJTMERGEINSERTCLAUSE = 11;
  public int JJTCOLUMN = 12;
  public int JJTRELOBJECTNAME = 13;
  public int JJTRELOBJECTNAMEEXT = 14;
  public int JJTTABLE = 15;
  public int JJTTABLEWITHALIAS = 16;
  public int JJTSELECT = 17;
  public int JJTSELECTBODY = 18;
  public int JJTPLAINSELECT = 19;
  public int JJTSETOPERATIONLIST = 20;
  public int JJTWITHLIST = 21;
  public int JJTWITHITEM = 22;
  public int JJTSELECTITEMSLIST = 23;
  public int JJTSELECTEXPRESSIONITEM = 24;
  public int JJTSELECTITEM = 25;
  public int JJTALLTABLECOLUMNS = 26;
  public int JJTALIAS = 27;
  public int JJTFUNCTIONITEM = 28;
  public int JJTPIVOTFORCOLUMNS = 29;
  public int JJTPIVOTFUNCTIONITEMS = 30;
  public int JJTPIVOTSINGLEINITEMS = 31;
  public int JJTEXPRESSIONLISTITEM = 32;
  public int JJTPIVOTMULTIINITEMS = 33;
  public int JJTPIVOT = 34;
  public int JJTPIVOTXML = 35;
  public int JJTINTOCLAUSE = 36;
  public int JJTFROMITEM = 37;
  public int JJTVALUESLIST = 38;
  public int JJTLATERALSUBSELECT = 39;
  public int JJTSUBJOIN = 40;
  public int JJTJOINSLIST = 41;
  public int JJTJOINEREXPRESSION = 42;
  public int JJTWHERECLAUSE = 43;
  public int JJTORACLEHIERARCHICALQUERYCLAUSE = 44;
  public int JJTGROUPBYCOLUMNREFERENCES = 45;
  public int JJTHAVING = 46;
  public int JJTORDERBYELEMENTS = 47;
  public int JJTORDERBYELEMENT = 48;
  public int JJTLIMIT = 49;
  public int JJTOFFSET = 50;
  public int JJTFETCH = 51;
  public int JJTTOP = 52;
  public int JJTSKIP = 53;
  public int JJTGETORACLEHINT = 54;
  public int JJTFIRST = 55;
  public int JJTEXPRESSION = 56;
  public int JJTOREXPRESSION = 57;
  public int JJTANDEXPRESSION = 58;
  public int JJTCONDITION = 59;
  public int JJTREGULARCONDITION = 60;
  public int JJTSQLCONDITION = 61;
  public int JJTINEXPRESSION = 62;
  public int JJTBETWEEN = 63;
  public int JJTLIKEEXPRESSION = 64;
  public int JJTISNULLEXPRESSION = 65;
  public int JJTEXISTSEXPRESSION = 66;
  public int JJTSQLEXPRESSIONLIST = 67;
  public int JJTSIMPLEEXPRESSIONLIST = 68;
  public int JJTSIMPLEEXPRESSIONLISTATLEASTTWOITEMS = 69;
  public int JJTCOMPARISONITEM = 70;
  public int JJTALLCOMPARISONEXPRESSION = 71;
  public int JJTANYCOMPARISONEXPRESSION = 72;
  public int JJTSIMPLEEXPRESSION = 73;
  public int JJTCONCATEXPRESSION = 74;
  public int JJTBITWISEANDOR = 75;
  public int JJTADDITIVEEXPRESSION = 76;
  public int JJTMULTIPLICATIVEEXPRESSION = 77;
  public int JJTBITWISEXOR = 78;
  public int JJTPRIMARYEXPRESSION = 79;
  public int JJTJDBCNAMEDPARAMETER = 80;
  public int JJTUSERVARIABLE = 81;
  public int JJTNUMERICBIND = 82;
  public int JJTJSONEXPRESSION = 83;
  public int JJTINTERVALEXPRESSION = 84;
  public int JJTWITHINGROUPEXPRESSION = 85;
  public int JJTKEEPEXPRESSION = 86;
  public int JJTANALYTICEXPRESSION = 87;
  public int JJTWINDOWELEMENT = 88;
  public int JJTWINDOWOFFSET = 89;
  public int JJTEXTRACTEXPRESSION = 90;
  public int JJTCASTEXPRESSION = 91;
  public int JJTCASEWHENEXPRESSION = 92;
  public int JJTWHENTHENSEARCHCONDITION = 93;
  public int JJTWHENTHENVALUE = 94;
  public int JJTROWCONSTRUCTOR = 95;
  public int JJTEXECUTE = 96;
  public int JJTFUNCTION = 97;
  public int JJTMYSQLGROUPCONCAT = 98;
  public int JJTSUBSELECT = 99;
  public int JJTCREATEINDEX = 100;
  public int JJTCREATETABLE = 101;
  public int JJTCOLDATATYPE = 102;
  public int JJTCREATEVIEW = 103;
  public int JJTCREATEPARAMETER = 104;
  public int JJTALIST = 105;
  public int JJTCOLUMNSNAMESLIST = 106;
  public int JJTDROP = 107;
  public int JJTTRUNCATE = 108;
  public int JJTALTER = 109;


  public String[] jjtNodeName = {
    "Statement",
    "SingleStatement",
    "Statements",
    "Set",
    "Update",
    "Replace",
    "ListExpressionItem",
    "Insert",
    "Delete",
    "Merge",
    "MergeUpdateClause",
    "MergeInsertClause",
    "Column",
    "RelObjectName",
    "RelObjectNameExt",
    "Table",
    "TableWithAlias",
    "Select",
    "SelectBody",
    "PlainSelect",
    "SetOperationList",
    "WithList",
    "WithItem",
    "SelectItemsList",
    "SelectExpressionItem",
    "SelectItem",
    "AllTableColumns",
    "Alias",
    "FunctionItem",
    "PivotForColumns",
    "PivotFunctionItems",
    "PivotSingleInItems",
    "ExpressionListItem",
    "PivotMultiInItems",
    "Pivot",
    "PivotXml",
    "IntoClause",
    "FromItem",
    "ValuesList",
    "LateralSubSelect",
    "SubJoin",
    "JoinsList",
    "JoinerExpression",
    "WhereClause",
    "OracleHierarchicalQueryClause",
    "GroupByColumnReferences",
    "Having",
    "OrderByElements",
    "OrderByElement",
    "Limit",
    "Offset",
    "Fetch",
    "Top",
    "Skip",
    "getOracleHint",
    "First",
    "Expression",
    "OrExpression",
    "AndExpression",
    "Condition",
    "RegularCondition",
    "SQLCondition",
    "InExpression",
    "Between",
    "LikeExpression",
    "IsNullExpression",
    "ExistsExpression",
    "SQLExpressionList",
    "SimpleExpressionList",
    "SimpleExpressionListAtLeastTwoItems",
    "ComparisonItem",
    "AllComparisonExpression",
    "AnyComparisonExpression",
    "SimpleExpression",
    "ConcatExpression",
    "BitwiseAndOr",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "BitwiseXor",
    "PrimaryExpression",
    "JdbcNamedParameter",
    "UserVariable",
    "NumericBind",
    "JsonExpression",
    "IntervalExpression",
    "WithinGroupExpression",
    "KeepExpression",
    "AnalyticExpression",
    "WindowElement",
    "WindowOffset",
    "ExtractExpression",
    "CastExpression",
    "CaseWhenExpression",
    "WhenThenSearchCondition",
    "WhenThenValue",
    "RowConstructor",
    "Execute",
    "Function",
    "MySQLGroupConcat",
    "SubSelect",
    "CreateIndex",
    "CreateTable",
    "ColDataType",
    "CreateView",
    "CreateParameter",
    "AList",
    "ColumnsNamesList",
    "Drop",
    "Truncate",
    "Alter",
  };
}
